// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: proto/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulseRouter_StreamTelemetry_FullMethodName = "/telemetry.PulseRouter/StreamTelemetry"
)

// PulseRouterClient is the client API for PulseRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The PulseRouter acts as the central intake for all REVENANT telemetry
type PulseRouterClient interface {
	// Streams high-speed telemetry from REVENANT.WIN and REVENANT.LSM
	StreamTelemetry(ctx context.Context, in *TelemetryEvent, opts ...grpc.CallOption) (*RoutingResponse, error)
}

type pulseRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseRouterClient(cc grpc.ClientConnInterface) PulseRouterClient {
	return &pulseRouterClient{cc}
}

func (c *pulseRouterClient) StreamTelemetry(ctx context.Context, in *TelemetryEvent, opts ...grpc.CallOption) (*RoutingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingResponse)
	err := c.cc.Invoke(ctx, PulseRouter_StreamTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PulseRouterServer is the server API for PulseRouter service.
// All implementations must embed UnimplementedPulseRouterServer
// for forward compatibility.
//
// The PulseRouter acts as the central intake for all REVENANT telemetry
type PulseRouterServer interface {
	// Streams high-speed telemetry from REVENANT.WIN and REVENANT.LSM
	StreamTelemetry(context.Context, *TelemetryEvent) (*RoutingResponse, error)
	mustEmbedUnimplementedPulseRouterServer()
}

// UnimplementedPulseRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulseRouterServer struct{}

func (UnimplementedPulseRouterServer) StreamTelemetry(context.Context, *TelemetryEvent) (*RoutingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedPulseRouterServer) mustEmbedUnimplementedPulseRouterServer() {}
func (UnimplementedPulseRouterServer) testEmbeddedByValue()                     {}

// UnsafePulseRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseRouterServer will
// result in compilation errors.
type UnsafePulseRouterServer interface {
	mustEmbedUnimplementedPulseRouterServer()
}

func RegisterPulseRouterServer(s grpc.ServiceRegistrar, srv PulseRouterServer) {
	// If the following call panics, it indicates UnimplementedPulseRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulseRouter_ServiceDesc, srv)
}

func _PulseRouter_StreamTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulseRouterServer).StreamTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulseRouter_StreamTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulseRouterServer).StreamTelemetry(ctx, req.(*TelemetryEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// PulseRouter_ServiceDesc is the grpc.ServiceDesc for PulseRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulseRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.PulseRouter",
	HandlerType: (*PulseRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamTelemetry",
			Handler:    _PulseRouter_StreamTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telemetry.proto",
}
